### ISSUE TITLE
TypeError: Cannot read property 'rules' of undefined

### ISSUE THREAD

**Issue by mikeerickson** [nfischer/shelljs-transpiler#23] opened 2016-08-23 20:32 UTC
Just installed and tried to apply to one of my many bash scripts, boom!

```
 $ sh2js new-branch.sh
Unable to parse script
/usr/local/lib/node_modules/shelljs-transpiler/lib/ohm/dist/ohm.js:5763
  var description = grammar.rules[this.ruleName].description;
                           ^

TypeError: Cannot read property 'rules' of undefined
    at Apply.pexprs.Apply.toFailure (/usr/local/lib/node_modules/shelljs-transpiler/lib/ohm/dist/ohm.js:5763:28)
    at /usr/local/lib/node_modules/shelljs-transpiler/lib/ohm/dist/ohm.js:5776:50
    at Array.map (native)
    at Alt.pexprs.Alt.toFailure (/usr/local/lib/node_modules/shelljs-transpiler/lib/ohm/dist/ohm.js:5776:23)
    at Not.pexprs.Not.toFailure (/usr/local/lib/node_modules/shelljs-transpiler/lib/ohm/dist/ohm.js:5754:26)
    at Object.State.processFailure (/usr/local/lib/node_modules/shelljs-transpiler/lib/ohm/dist/ohm.js:2780:41)
    at Not.pexprs.Not.eval (/usr/local/lib/node_modules/shelljs-transpiler/lib/ohm/dist/ohm.js:4685:11)
    at Object.State.eval (/usr/local/lib/node_modules/shelljs-transpiler/lib/ohm/dist/ohm.js:2902:20)
    at Seq.pexprs.Seq.eval (/usr/local/lib/node_modules/shelljs-transpiler/lib/ohm/dist/ohm.js:4623:16)
    at Object.State.eval (/usr/local/lib/node_modules/shelljs-transpiler/lib/ohm/dist/ohm.js:2902:20)

```

**Comment by nfischer** [comment] 2016-08-23 21:00
@mikeerickson I've seen this sort of thing too, and I'm not quite sure what's causing it (it's related to a dependency). Would you be able to send me a minimal bash script that gives that error?

**Comment by mikeerickson** [comment] 2016-08-23 21:23
Seems the rest of my scripts work, but here is the one that always throws the error

```bash
#!/bin/bash

# Colors
ESC_SEQ="\x1b["
COL_RESET=$ESC_SEQ"39;49;00m"
COL_RED=$ESC_SEQ"31;01m"
COL_GREEN=$ESC_SEQ"32;01m"
COL_YELLOW=$ESC_SEQ"33;01m"
COL_BLUE=$ESC_SEQ"34;01m"
COL_MAGENTA=$ESC_SEQ"35;01m"
COL_CYAN=$ESC_SEQ"36;01m"
COL_WHITE=$ESC_SEQ"37;01m"


BRANCH=$1
if [ -z "$1" ]
  then
		BRANCH=""
fi

echo -e "\n"
if [ -z "$BRANCH" ]; then
   echo -e "$COL_RED You mush supply <branch> name"
else
	 echo -e "$COL_CYAN Creating$COL_WHITE <$BRANCH>$COL_CYAN branch...$COL_RESET"
   git fetch upstream 5_0_refactor
   git checkout -b $BRANCH upstream/5_0_refactor
fi
```

**Comment by nfischer** [comment] 2016-08-24 00:47
@mikeerickson This should be fixed on Master. I'll get a patch release out soon (so reinstalling the package should get the fix).

The only thing that won't work is that ShellJS `echo()` behaves like `-e` by default, and `echo('-e', 'foo')` will print `-e foo` instead of `foo`. Since this is a bug with ShellJS, I filed it upstream: shelljs/shelljs#510. I'll have this fixed shortly.

Also, if any of your scripts misbehave, feel free to file a bug report here and I'll take a look.

**Closed by nfischer** 2016-08-24 00:47 UTC

**Comment by mikeerickson** [comment] 2016-08-24 02:41
@nfischer I have another issue but dont have all the details as I dont have the code with me.  I will submit the Issue tomorrow (in short, having problems loading `shelljs/global` (yes I do have shelljs installed globally)

**Comment by mikeerickson** [comment] 2016-08-25 03:16
@nfischer I have managed to get my scripts running, however, the color output is not working as it does in the .sh scripts?   They are converted to be part of env object (env.COL_GREEN)

Further, these colors are supposed to be imported from `colors.sh` but this file fails in transpilation as well (as this issue originally posted).

```
#!/bin/bash

# Colors
ESC_SEQ="\x1b["
COL_RESET=$ESC_SEQ"39;49;00m"
COL_RED=$ESC_SEQ"31;01m"
COL_GREEN=$ESC_SEQ"32;01m"
COL_YELLOW=$ESC_SEQ"33;01m"
COL_BLUE=$ESC_SEQ"34;01m"
COL_MAGENTA=$ESC_SEQ"35;01m"
COL_CYAN=$ESC_SEQ"36;01m"
COL_WHITE=$ESC_SEQ"37;01m"
```

**Comment by nfischer** [comment] 2016-08-25 04:25
Ah, I think the issue is that the variable isn't being translated properly. I'll open an issue for that.

The colors should be working as expected, however. Let me know if that's not the case.
